# Generated by Django 3.2.8 on 2021-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
