# Generated by Django 3.2.8 on 2021-10-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('creationdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('cows', models.IntegerField(blank=True, null=True)),
                ('milk', models.IntegerField(blank=True, null=True)),
                ('feed', models.IntegerField(blank=True, null=True)),
                ('cowmilk', models.IntegerField(blank=True, null=True)),
                ('efficiecy', models.IntegerField(blank=True, null=True)),
                ('conversion', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('obs', models.CharField(blank=True, max_length=300, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
        ),
    ]
