# Generated by Django 3.2.8 on 2021-10-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creationdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
