# Generated by Django 3.2.8 on 2021-10-31 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pday',
            old_name='efficiecy',
            new_name='efficiency',
        ),
    ]
