# Generated by Django 3.2.8 on 2021-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_efficiecy_pday_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pday',
            name='conversion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pday',
            name='cowmilk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pday',
            name='cows',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pday',
            name='efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pday',
            name='feed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pday',
            name='milk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
