# Generated by Django 3.2.8 on 2021-10-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211028_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='obs',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
